services:
  lambda:
    container_name: lastfm-now-playing
    image: lastfm-now-playing
    build:
      context: .
      dockerfile: Dockerfile
      target: local-runtime
    platform: linux/amd64
    env_file:
      - ./.env
